### ISSUE TITLE
publish docker file

### ISSUE THREAD

**Issue by danstarns** [rocket-connect/graphql-debugger#183]
The PR: 
* https://github.com/rocket-connect/graphql-debugger/pull/154

Gave us a [docker file](https://github.com/rocket-connect/graphql-debugger/blob/main/docker/Dockerfile) and a [running test suite against it](https://github.com/rocket-connect/graphql-debugger/blob/main/.github/workflows/quality.yml#L25).

We should publish this to the docker registry so that users can pull it and use it in their environments.  

This should be done on a [release](https://github.com/rocket-connect/graphql-debugger/blob/main/.github/workflows/release.yml)

**Comment by afro-coder** [comment]
I've started work on this will open a draft PR shortly, a bit rusty with this so trying it on my repo first!
