### ISSUE TITLE
Add dependency checking bot

### ISSUE THREAD

**Issue by danstarns** [rocket-connect/graphql-debugger#23]
- https://github.com/rocket-connect/graphql-debugger/pull/21

## Problem

Dependencies get out of date quickly and this can lead to security and developer tooling issues. 

## Solution

Let's adopt something in the pipelines that automatically checks and makes prs to update dependencies.

**Comment by Tohaker** [comment]
I've used both Dependabot and Renovate to achieve this in the past, I think going with Dependabot first is a good option as it's well maintained by Github

**Comment by danstarns** [comment]
Closed by: 
* https://github.com/rocket-connect/graphql-debugger/commit/7a914df81a1c836a2d4c852bf5a00a0d1c2b02d2
