### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by danstarns** [rocket-connect/graphql-debugger#33]
## Problem
The layout has been 'hacked' together to be made to look like [graphiql](https://github.com/graphql/graphiql). 

This theme was chosen so it's the most familiar to other developers and it has already been battle-tested. 

We find ourselves with a large file where all the layout is defined, not to mention that all the slide panes and panels are of fixed width and height

## Solution

We should refactor and rebuild the frontend layout so that users can expand, scale, and hide panels, to that the same as graphiql.

**Comment by danstarns** [comment]
Its worth leveraging the discussion here about graphiql 2's design: 

* https://github.com/graphql/graphiql/discussions/2216

**Comment by kreshnnikgashi** [comment]
- [ ] #45

**Comment by danstarns** [comment]
* https://github.com/rocket-connect/graphql-debugger/issues/46
