### ISSUE TITLE
Display precise start and end times

### ISSUE THREAD

**Issue by danstarns** [rocket-connect/graphql-debugger#6]
* https://github.com/rocket-connect/graphql-debugger/issues/4

## Problem

The trace viewer only displays the end time for each trace displayed. 

<img width="1716" alt="Screenshot 2023-09-13 at 21 20 01" src="https://github.com/rocket-connect/graphql-debugger/assets/35999252/a858801a-e0be-4209-88d5-07a05d744bea">

But we should be displaying the start and end times. 

## Solution

We should display both the start and end times in the trace list, plus add the start and end times to the trace view. 

<img width="1716" alt="Screenshot 2023-09-13 at 21 22 12" src="https://github.com/rocket-connect/graphql-debugger/assets/35999252/e1677b70-b362-4007-bd53-6316974f1900">

**Comment by danstarns** [comment]
Related: https://github.com/rocket-connect/graphql-debugger/pull/22#issuecomment-1716514848

**Comment by Tohaker** [comment]
How does this look? 
![image](https://github.com/rocket-connect/graphql-debugger/assets/33665681/5f0ab063-a641-4c0f-a723-eb383d664f5f)

I didn't want to bog the UI down with `Start` and `End` in so many places, so hopefully the line between the times conveys the message that this is a timeline.

I also increased the precision of the timestamps to 3dp and ensured the duration was using the right SI units

**Comment by danstarns** [comment]
@Tohaker I feel like this is a good solution for now and provides value, however, it's quickly apparent that the trace viewer is limited in real estate. 

I have made an issue to track the work of making a full-screen trace viewer 

* https://github.com/rocket-connect/graphql-debugger/issues/45
